import React, { useState, useEffect } from 'react';

import IngredientForm from './IngredientForm';
import IngredientList from './IngredientList';
import Search from './Search';

const Ingredients = () => {
  const [ userIngredients, setUserIngredients ] = useState([])

  // useEffect acts like componentDidUpdate, which runs after every
  // component update (re-render). If there are no external dependencies
  // (ie. variables or data defined inside component but outside of the 
  // useEffect function, setUserIngredients is an exception generated by
  // useState) in the second argument, then useEffect will act like 
  // componentDidMount and runs only once after first component render.
  useEffect(() => {
    fetch('https://react-hooks-da136.firebaseio.com/ingredients.json')
    .then(response => response.json())
    .then(responseData => {
      const fetchedIngredients = []
      for (const key in responseData) {
          fetchedIngredients.push({
            id: key,
            title: responseData[key].title,
            amount: responseData[key].amount
          })
        }
      setUserIngredients(fetchedIngredients)
    })
  }, [])

  const addIngredientHandler = ingredient => {
    // use built-in JS fetch API instead of axios.
    fetch('https://react-hooks-da136.firebaseio.com/ingredients.json', {
      method: 'POST',
      // axios converts JS object or array to JSON format,
      // and adds headers by default to inform database that json is
      // incoming
      body: JSON.stringify(ingredient),
      headers: { 'Content-Type': 'application/json' }   
    }).then(response => {
      return response.json() // converts JSON to normal JS code
    }).then(responseData => {
      // responseData contains an auto generated, unique ID from firebase
      setUserIngredients(prevIngredients => (
        [...prevIngredients, {
          id: responseData.name, ...ingredient
        }]
      ))
    })
  }

  const removeIngredientHandler = ingredientId => { 
    setUserIngredients(prevIngredients => (
      prevIngredients.filter(ingredient => ( 
        ingredient.id !== ingredientId 
      ))
    ))
  }

  return (
    <div className="App">
      <IngredientForm onAddIngredient={addIngredientHandler} />

      <section>
        <Search />
        <IngredientList 
          onRemoveItem={removeIngredientHandler}
          ingredients={userIngredients}
        />
      </section>
    </div>
  );
}

export default Ingredients;
